name: Generate Geodata

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь
  workflow_dispatch: # Возможность запустить вручную

jobs:
  generate-geodata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y golang git

      - name: Генерация geosite.dat (список доменов)
        run: |
          git clone https://github.com/v2fly/domain-list-community.git
          cd domain-list-community
          go mod download
          go run ./ --datapath=data/custom
          mkdir -p ../geodata
          mv dlc.dat ../geodata/geosite.dat

      - name: Генерация geoip.dat (список IP)
        run: |
          git clone https://github.com/v2fly/geoip.git
          cd geoip
          go mod download
          go run ./ -c config.json
          mkdir -p ../geodata
          mv output/dat/geoip.dat ../geodata/geoip.dat

      - name: Commit и Push изменений
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add geodata/geosite.dat geodata/geoip.dat
          git commit -m "Автообновление geosite.dat и geoip.dat $(date +'%Y-%m-%d')"
          git push
