name: Generate Geosite

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь
  workflow_dispatch: # Возможность запустить вручную

jobs:
  generate-dlc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Клонирование domain-list-community
        run: |
          git clone https://github.com/v2fly/domain-list-community.git
          cd domain-list-community
          go mod download

      - name: Копирование YAML-файлов в DLC-формат
        run: |
          mkdir -p domain-list-community/data/custom
          cd Clash/Domains
          if [ ! -f *.yaml ]; then
            echo "Ошибка: в Clash/Domains нет YAML-файлов" >&2
            exit 1
          fi
          for file in *.yaml; do
            if [ -f "$file" ]; then
              category=$(basename "$file" .yaml)
              echo "# Custom rules for $category" > ../../domain-list-community/data/custom/$category
              # Извлекаем строки из payload и преобразуем в формат domain:
              sed -n '/payload:/,$p' "$file" | grep '^- "' | sed 's/^- "\(.*\)"/domain:\1/' >> ../../domain-list-community/data/custom/$category
            fi
          done
          # Проверка, что файлы созданы
          ls -la ../../domain-list-community/data/custom/

      - name: Генерация dlc.dat
        run: |
          cd domain-list-community
          go run ./ --datapath=data/custom
          mkdir -p ../Geodata
          mv dlc.dat ../Geodata/geosite.dat
          # Проверка, что файл существует
          ls -la ../Geodata/
          if [ ! -f "../Geodata/geosite.dat" ]; then
            echo "Ошибка: geosite.dat не был сгенерирован" >&2
            exit 1
          fi

      - name: Проверка изменений
        id: check_changes
        run: |
          git add Geodata/geosite.dat
          git diff --cached --quiet || echo "changed=true" >> $GITHUB_ENV
          # Вывод для отладки
          echo "Изменения обнаружены: ${{ env.changed }}"

      - name: Commit и Push изменений
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Обновление geosite.dat $(date +'%Y-%m-%d')"
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main