name: Generate GeoIP

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь
  workflow_dispatch: # Возможность запустить вручную

jobs:
  generate-geoip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Клонирование geoip
        run: |
          git clone https://github.com/v2fly/geoip.git
          cd geoip
          go mod download

      - name: Подготовка текстового файла из Discord_IP.yaml
        run: |
          mkdir -p geoip/input
          awk '/payload:/{next} {print $2}' Discord_IP.yaml > geoip/input/discord.lst
          # Проверка содержимого для отладки
          cat geoip/input/discord.lst
          ls -la geoip/input/

      - name: Копирование файла в корень geoip
        run: |
          cd geoip
          cp input/discord.lst .
          ls -la .

      - name: Генерация geoip.dat (попытка без конфига)
        run: |
          cd geoip
          go run ./  # Пробуем запустить без config.json, как в чужом workflow
          mkdir -p ../geodata
          if [ -f "output/geoip.dat" ]; then
            mv output/geoip.dat ../geodata/geoip.dat
          else
            echo "Ошибка: geoip.dat не был сгенерирован" >&2
            exit 1
          fi
          ls -la ../geodata/

      - name: Проверка изменений
        id: check_changes
        run: |
          git add geodata/geoip.dat
          git diff --cached --quiet || echo "changed=true" >> $GITHUB_ENV
          echo "Изменения обнаружены: ${{ env.changed }}"

      - name: Commit и Push изменений
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Обновление geoip.dat $(date +'%Y-%m-%d')"
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
