name: Generate Empty GeoIP

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в 00:00 UTC
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create empty geoip.mmdb
        run: |
          echo -n -e "\xab\xcd\xefMaxMind.com" > geoip.mmdb

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add geoip.mmdb
          git commit -m "Generate minimal geoip.mmdb" || echo "No changes to commit"
          git push
